"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AdminUser = exports.Ticket = exports.Payment = exports.Booking = exports.Flight = void 0;
const Flight_1 = require("./Flight");
Object.defineProperty(exports, "Flight", { enumerable: true, get: function () { return Flight_1.Flight; } });
const Booking_1 = require("./Booking");
Object.defineProperty(exports, "Booking", { enumerable: true, get: function () { return Booking_1.Booking; } });
const Payment_1 = require("./Payment");
Object.defineProperty(exports, "Payment", { enumerable: true, get: function () { return Payment_1.Payment; } });
const Ticket_1 = require("./Ticket");
Object.defineProperty(exports, "Ticket", { enumerable: true, get: function () { return Ticket_1.Ticket; } });
const AdminUser_1 = require("./AdminUser");
Object.defineProperty(exports, "AdminUser", { enumerable: true, get: function () { return AdminUser_1.AdminUser; } });
Flight_1.Flight.hasMany(Booking_1.Booking, { foreignKey: 'flight_id', as: 'bookings' });
Booking_1.Booking.belongsTo(Flight_1.Flight, { foreignKey: 'flight_id', as: 'flight' });
Booking_1.Booking.hasMany(Payment_1.Payment, { foreignKey: 'booking_id', as: 'payments' });
Payment_1.Payment.belongsTo(Booking_1.Booking, { foreignKey: 'booking_id', as: 'booking' });
Booking_1.Booking.hasMany(Ticket_1.Ticket, { foreignKey: 'booking_id', as: 'tickets' });
Ticket_1.Ticket.belongsTo(Booking_1.Booking, { foreignKey: 'booking_id', as: 'booking' });
